### ISSUE TITLE
Check argument type in removeOnce and findOnce

### ISSUE THREAD

**Issue by theodoreb** [RobLoach/jquery-once#28]
Basically factoring 

```
    id = id || "once";
    if (typeof id !== "string") {
      throw new Error("jQuery.once() parameter must be a string");
    }
    // Build the name for the data identifier. Generate a new unique id if the
    // id parameter is not provided.
    var name = "jquery-once-" + id;
```

into it's own function and use in once, removeOnce and findOnce

**Comment by RobLoach** [comment]
:+1: .... Do we actually need to check the type validity of `id`? I suppose it does help in people's usage of it.

**Comment by theodoreb** [comment]
Yeah I've seen a lot of people use `$('.mqldsk').once(function () {})`, it'll help them know what's wrong when upgrading.
