### ISSUE TITLE
Add Typescript Suport with @types

### ISSUE THREAD

**Issue by olavorn** [RobLoach/jquery-once#42]
Just let create the type definition in the package and point it in packages.json using 

//packages.json
{...
types : jquery-once.d.ts
...}

**Comment by RobLoach** [comment]
Not quite familiar with TypeScript, or `types`. Do you have some documentation around it? `jquery-once.d.ts` doesn't exist in the repo, is it needed?

**Comment by olavorn** [comment]
Just submited [pull request](https://github.com/RobLoach/jquery-once/pull/43) with all wrapped.

**Comment by RobLoach** [comment]
Thanks a lot! Merged :+1:
