### ISSUE TITLE
Document preferable usage with for() instead of each()

### ISSUE THREAD

**Issue by andypost** [RobLoach/jquery-once#48]
Or at least it makes sense to add few lines about it as suggestion

**Comment by RobLoach** [comment]
`for()`?

**Comment by andypost** [comment]
I mean `for()` loop, like https://www.drupal.org/node/1428524#comment-6163962

**Comment by RobLoach** [comment]
Documenting jQuery usage seems outside of the scope for jQuery Once.  jQuery Once doesn't care which one you use. Could be a good blog post though! 
https://www.sitepoint.com/speed-question-jquery-each-vs-loop/

Perhaps there have been some good performance improvements in jQuery 3.x?
