### ISSUE TITLE
UMD for CommonJS breaks when an element with the ID "exports" is present

### ISSUE THREAD

**Issue by Sam152** [RobLoach/jquery-once#91]
Similar issue here: https://github.com/umdjs/umd/issues/35

The committed fix was `typeof exports === 'object' && typeof exports.nodeName !== 'string'`

**Comment by RobLoach** [comment]
Thanks for the report... Would you mind submitting a PR for this?

**Comment by Sam152** [comment]
Sure, created here: https://github.com/RobLoach/jquery-once/pull/92
